/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedAppImport } from './routes/_authenticated/_app'
import { Route as AuthRegisterIndexImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as AuthenticatedAppIndexImport } from './routes/_authenticated/_app/index'
import { Route as AuthenticatedAppStrategyEditorIndexImport } from './routes/_authenticated/_app/strategy-editor/index'
import { Route as AuthenticatedAppSetupIndexImport } from './routes/_authenticated/_app/setup/index'
import { Route as AuthenticatedAppLiveExchangeIndexImport } from './routes/_authenticated/_app/live-exchange/index'
import { Route as AuthenticatedAppHomeIndexImport } from './routes/_authenticated/_app/home/index'
import { Route as AuthenticatedAppBotStudioIndexImport } from './routes/_authenticated/_app/bot-studio/index'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedAppRoute = AuthenticatedAppImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthRegisterIndexRoute = AuthRegisterIndexImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedAppIndexRoute = AuthenticatedAppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

const AuthenticatedAppStrategyEditorIndexRoute =
  AuthenticatedAppStrategyEditorIndexImport.update({
    id: '/strategy-editor/',
    path: '/strategy-editor/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppSetupIndexRoute = AuthenticatedAppSetupIndexImport.update(
  {
    id: '/setup/',
    path: '/setup/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any,
)

const AuthenticatedAppLiveExchangeIndexRoute =
  AuthenticatedAppLiveExchangeIndexImport.update({
    id: '/live-exchange/',
    path: '/live-exchange/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppHomeIndexRoute = AuthenticatedAppHomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

const AuthenticatedAppBotStudioIndexRoute =
  AuthenticatedAppBotStudioIndexImport.update({
    id: '/bot-studio/',
    path: '/bot-studio/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAppImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_app/bot-studio/': {
      id: '/_authenticated/_app/bot-studio/'
      path: '/bot-studio'
      fullPath: '/bot-studio'
      preLoaderRoute: typeof AuthenticatedAppBotStudioIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/home/': {
      id: '/_authenticated/_app/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedAppHomeIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/live-exchange/': {
      id: '/_authenticated/_app/live-exchange/'
      path: '/live-exchange'
      fullPath: '/live-exchange'
      preLoaderRoute: typeof AuthenticatedAppLiveExchangeIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/setup/': {
      id: '/_authenticated/_app/setup/'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedAppSetupIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/strategy-editor/': {
      id: '/_authenticated/_app/strategy-editor/'
      path: '/strategy-editor'
      fullPath: '/strategy-editor'
      preLoaderRoute: typeof AuthenticatedAppStrategyEditorIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppBotStudioIndexRoute: typeof AuthenticatedAppBotStudioIndexRoute
  AuthenticatedAppHomeIndexRoute: typeof AuthenticatedAppHomeIndexRoute
  AuthenticatedAppLiveExchangeIndexRoute: typeof AuthenticatedAppLiveExchangeIndexRoute
  AuthenticatedAppSetupIndexRoute: typeof AuthenticatedAppSetupIndexRoute
  AuthenticatedAppStrategyEditorIndexRoute: typeof AuthenticatedAppStrategyEditorIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppBotStudioIndexRoute: AuthenticatedAppBotStudioIndexRoute,
  AuthenticatedAppHomeIndexRoute: AuthenticatedAppHomeIndexRoute,
  AuthenticatedAppLiveExchangeIndexRoute:
    AuthenticatedAppLiveExchangeIndexRoute,
  AuthenticatedAppSetupIndexRoute: AuthenticatedAppSetupIndexRoute,
  AuthenticatedAppStrategyEditorIndexRoute:
    AuthenticatedAppStrategyEditorIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedAppRouteWithChildren
  '/': typeof AuthenticatedAppIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/bot-studio': typeof AuthenticatedAppBotStudioIndexRoute
  '/home': typeof AuthenticatedAppHomeIndexRoute
  '/live-exchange': typeof AuthenticatedAppLiveExchangeIndexRoute
  '/setup': typeof AuthenticatedAppSetupIndexRoute
  '/strategy-editor': typeof AuthenticatedAppStrategyEditorIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRouteWithChildren
  '/': typeof AuthenticatedAppIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/bot-studio': typeof AuthenticatedAppBotStudioIndexRoute
  '/home': typeof AuthenticatedAppHomeIndexRoute
  '/live-exchange': typeof AuthenticatedAppLiveExchangeIndexRoute
  '/setup': typeof AuthenticatedAppSetupIndexRoute
  '/strategy-editor': typeof AuthenticatedAppStrategyEditorIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/_authenticated/_app/bot-studio/': typeof AuthenticatedAppBotStudioIndexRoute
  '/_authenticated/_app/home/': typeof AuthenticatedAppHomeIndexRoute
  '/_authenticated/_app/live-exchange/': typeof AuthenticatedAppLiveExchangeIndexRoute
  '/_authenticated/_app/setup/': typeof AuthenticatedAppSetupIndexRoute
  '/_authenticated/_app/strategy-editor/': typeof AuthenticatedAppStrategyEditorIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/bot-studio'
    | '/home'
    | '/live-exchange'
    | '/setup'
    | '/strategy-editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/bot-studio'
    | '/home'
    | '/live-exchange'
    | '/setup'
    | '/strategy-editor'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_app'
    | '/_authenticated/_app/'
    | '/auth/login/'
    | '/auth/register/'
    | '/_authenticated/_app/bot-studio/'
    | '/_authenticated/_app/home/'
    | '/_authenticated/_app/live-exchange/'
    | '/_authenticated/_app/setup/'
    | '/_authenticated/_app/strategy-editor/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/auth/login/",
        "/auth/register/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_app"
      ]
    },
    "/_authenticated/_app": {
      "filePath": "_authenticated/_app.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_app/",
        "/_authenticated/_app/bot-studio/",
        "/_authenticated/_app/home/",
        "/_authenticated/_app/live-exchange/",
        "/_authenticated/_app/setup/",
        "/_authenticated/_app/strategy-editor/"
      ]
    },
    "/_authenticated/_app/": {
      "filePath": "_authenticated/_app/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx"
    },
    "/auth/register/": {
      "filePath": "auth/register/index.tsx"
    },
    "/_authenticated/_app/bot-studio/": {
      "filePath": "_authenticated/_app/bot-studio/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/home/": {
      "filePath": "_authenticated/_app/home/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/live-exchange/": {
      "filePath": "_authenticated/_app/live-exchange/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/setup/": {
      "filePath": "_authenticated/_app/setup/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/strategy-editor/": {
      "filePath": "_authenticated/_app/strategy-editor/index.tsx",
      "parent": "/_authenticated/_app"
    }
  }
}
ROUTE_MANIFEST_END */
